version: "3"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    container_name: lab8-frontend
    command: npm run start
    ports:
      - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true
  api:
    build: ./api
    command: npm run start
    container_name: lab8-backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      HOST: "127.0.0.1"
      MONGO_URL: "mongodb://api_db:27017/api"
    depends_on:
      - api_db
  api_db:
    image: "mongo:latest"
    volumes:
      - "mongodb_api:/data/db"
volumes:
  mongodb_api:
